### ISSUE TITLE
Need a Stream like APIs to retrieve DataPoints from ModelarDB.

### ISSUE THREAD

**Issue by dhavalsalwala** [ModelarData/ModelarDB#6]
Retrieval of decompressed data points from the DataPoint view is slower because the system reconstructs everything from Data Models for every Select operation.

**Comment by skejserjensen** [comment]
Commit b3087cbf8d80d151d25603b2dc6f0b75e044d5d9 extends ModelarDB's Apache Arrow Flight-based query interface with batching. So even if a user executes `SELECT * FROM DataPoint`, the resulting data points are transferred to the user's client in fixed-size batches. Does this feature solve your issue? I have not yet implemented support for the Apache Arrow Flight-based query interface in [PyModelarDB](https://github.com/ModelarData/PyModelarDB), but it should work with any Apache Arrow Flight compatible client. For example, the  following Python code convert the batches to Pandas:

``` python
from pyarrow import flight

client = flight.FlightClient('grpc://192.168.87.100:9999')
query = flight.Ticket('SELECT * FROM DataPoint')
for record_batch in client.do_get(query):
    pandas = record_batch.data.to_pandas()
```

**Comment by dhavalsalwala** [comment]
Hi @skejserjensen 
I think this is exactly what we wanted. Can we modify the batch size? or is it fixed on the ModelarDB?

If we use pyarrow, we can get rid of PyModelarDB, right? There are no dependencies on PyModelarDB. As far as our work is concerned, we are only interested in Data Points.

**Comment by skejserjensen** [comment]
At the moment the batch size is fixed to [1024 * JdbcToArrowConfig.DEFAULT_TARGET_BATCH_SIZE](https://github.com/ModelarData/ModelarDB/blob/b3087cbf8d80d151d25603b2dc6f0b75e044d5d9/src/main/scala/dk/aau/modelardb/remote/ArrowResultSet.scala#L27). However, the concept of a [Ticket](https://arrow.apache.org/docs/format/Flight.html) in Apache Arrow Flight is just sequence of bytes. So we could, e.g., encode the batch size as the first few bytes of the Ticket if different batch sizes are required. [PyModelarDB](https://github.com/ModelarData/PyModelarDB) implements [PEP 249](https://peps.python.org/pep-0249/) while [Apache Arrow Flight](https://arrow.apache.org/docs/format/Flight.html) is its own protocol, so if you are fine with using Apache Arrow Flight instead of PEP 249 then you do not need PyModelarDB. One major benefit of Apache Arrow Flight is that it is language agnostic while PEP 249 only works with Python, e.g., if you want to use ModelarDB from C++ you can use the [C++ Arrow library](https://github.com/apache/arrow/tree/master/cpp). I do plan to add support for ModelarDB's Apache Arrow Flight-based query interface to PyModelarDB by using PyArrow as a dependency. You can find more information about Apache Arrow Flights and its implementations here:
- Apache Arrow: https://github.com/apache/arrow
- Apache Arrow Flight RPC: https://arrow.apache.org/docs/format/Flight.html
- Java Apache Arrow Flight: https://arrow.apache.org/docs/java/reference/index.html and https://arrow.apache.org/docs/java/reference/org/apache/arrow/flight/package-frame.html
- Python Apache Arrow Flight: https://arrow.apache.org/docs/python/api.html and https://arrow.apache.org/docs/python/api/flight.html

**Comment by dhavalsalwala** [comment]
Thanks for the explanation. This looks good to me. I will look into Apache Arrow Flight / PyArrow and use it to implement a wrapper to get around for the time being. 

Ideally, we would be more comfortable accessing ModelarDB via PyModelarDB. So whenever it is ready, please let us know.

Also, can you confirm if the version of ModelarDB with Arrow Flight as a server is ready? A short example of ModelarDB with Arrow Flight Server is all we need. Once available, I will set up ModelarDB Server and try to connect it via pyarrow.

**Comment by skejserjensen** [comment]
I have created the pull-request ModelarData/PyModelarDB#1 which adds for support [Apache Arrow Flight](https://arrow.apache.org/docs/format/Flight.html) using [PyArrow](https://arrow.apache.org/docs/python/index.html) to [PyModelarDB](https://github.com/ModelarData/PyModelarDB). Feel free to review, test, and comment on the pull-request.

The [Apache Arrow Flight](https://arrow.apache.org/docs/format/Flight.html) interface as implemented in [dev/refactor-data-transfer](https://github.com/ModelarData/ModelarDB/commits/dev/refactor-data-transfer) should be ready, and it is the interface I primarily use. As part of [dev/refactor-data-transfer](https://github.com/ModelarData/ModelarDB/commits/dev/refactor-data-transfer) I have reverted to ModelarDB's original configuration format, as the new experimental configuration format did not bring the expected benefits and added a lot of unnecessary complexity and problems. The branch is not yet merged as I am still working on refactoring the data transfer component. So if you build ModelarDB from the latest commit in [dev/refactor-data-transfer](https://github.com/ModelarData/ModelarDB/commits/dev/refactor-data-transfer) and set `modelardb.interface` to `arrow` in `modelardb.conf` you should be able to query ModelarDB over [Apache Arrow Flight](https://github.com/ModelarData/ModelarDB/commits/dev/refactor-data-transfer).

**Comment by dhavalsalwala** [comment]
Thanks, @skejserjensen 

I see that you have added pyarrow support to PyModelarDB. As you explained, I will build the ModelarDB code from the latest commit in **dev/refactor-data-transfer**, and test the workflow via PyModelarDB.
